# Generated by Django 5.2.4 on 2025-07-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
