# Generated by Django 5.2.4 on 2025-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_created_at_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
